### PR TITLE
removed node_modules folder from Server folder

### PR DESCRIPTION
**Pull request by digitallymarked**
Removed node_modules folder as per issue #29

### CODE REVIEW

**Comment by adilanchian** [comment]
Hi @7re3k0 !

I greatly appreciate the PR! I am going to ask you for to changes:

1. Can you set the PR to actually merge into branch `release-1.0b3`? (That was my bad in the naming convention
2. Can you please verify that the `gitignore` file in the `SimpleAlerts-Server` includes all the proper ignored files for NodeJS? (Usually you can search it on GH and get a list of them)

I appreciate this man!

**Review by adilanchian — CHANGES_REQUESTED** [review]
Hi @7re3k0 !

I greatly appreciate the PR! I am going to ask you for to changes:

Can you set the PR to actually merge into branch release-1.0b3? (That was my bad in the naming convention
Can you please verify that the gitignore file in the SimpleAlerts-Server includes all the proper ignored files for NodeJS? (Usually you can search it on GH and get a list of them)
I appreciate this man!

**Comment by digitallymarked** [comment]
Updated .gitignore with a more extensive list

**Review by adilanchian — APPROVED** [review]

**Comment by adilanchian** [comment]
Thanks for your contribution @7re3k0 <3 

I appreciate you picking that up!

**Pull request merged**
